name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          lfs: true  # Activer Git LFS

      # Définir une variable d'environnement indiquant que l'on est dans GitHub Actions
      - name: Set environment variable for GitHub Actions
        run: echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q